[versions]
kotlin = "1.8.21"
dokka = "1.8.10"
ktor = "2.3.1"
kotlinx-datetime = "0.4.0"
napir = "2.6.1"
atomicfu = "0.20.2"
coroutines = "1.7.1"
android-lifecycle = "2.6.1"
androidx-startup = "1.1.1"
multiplatform-settings = "1.0.0"
okio = "3.3.0"
javalin = "5.5.0"
complete-kotlin = "1.1.0"
agp = "8.0.2"
maven-publish = "0.25.2"
cache4k = "0.11.0"
apollo-kotlin = "3.8.2"
stately = "1.2.5"
korlibs = "4.0.3"
detekt = "1.23.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
complete-kotlin = { id = "com.louiscad.complete-kotlin", version.ref = "complete-kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
kotlinx-atomicfu-plugin = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

napier = { module = "io.github.aakira:napier", version.ref = "napir" }

android-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "android-lifecycle" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }

multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

javalin = { module = "io.javalin:javalin", version.ref = "javalin" }

apollo-kotlin = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo-kotlin" }

cache4k = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k" }

stately = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }

krypto = { module = "com.soywiz.korlibs.krypto:krypto", version.ref = "korlibs" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-content-negotiation", "ktor-json"]
multiplatform-settings = ["multiplatform-settings-no-arg", "multiplatform-settings-coroutines"]