name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: general-info
    attributes:
      label: General Info
      options:
        - label: I checked for similar bug report
          required: true
        - label: I am using the latest version
          required: true
        - label: I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems
          required: true
  - type: input
    id: version
    attributes:
      label: Version(s)
      description: which supabase-kt versions are affected
      placeholder: 0.9.3
    validations:
      required: true
  - type: input
    id: target
    attributes:
      label: Kotlin Target(s) and their respective versions
      description: which kotlin targets are affected
      placeholder: JVM 17 and Android 14
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: What happened? (include your code)
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce (optional)
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ..
        2. ..
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
