name: Question
description: Template for questions
title: '[Question]: '
labels: ["question"]
body:
  - type: checkboxes
    id: general
    attributes:
      label: General info
      options:
        - label: I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.MD) page for similar problems
          required: true
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please ask your question
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
