name: Clear all Github actions caches
on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  clear-cache:
    name: Delete all caches
    runs-on: ubuntu-20.04
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}