name: Analyze code using detekt

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Analyze code using detekt
        run: ./gradlew detektAll --stacktrace
