name: release-to-maven-central
on:
  workflow_dispatch:
    inputs:
      repository_id:
        required: true
        type: string

env:
   GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
   GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   SONATYPE_REPOSITORY_ID: ${{ inputs.repository_id }}
   SONATYPE_PROFILE_ID: ${{ secrets.SONATYPE_REPOSITORY_ID }}

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - run: echo "Will start a Maven Central upload"

      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publishAllPublicationsToOssRepository
      - name: Close and release
        run: ./gradlew closeAndRelease