name: Test project

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        command: [
          'jvmTest testDebugUnitTest testReleaseUnitTest',
          'jsTest',
          'iosX64Test iosSimulatorArm64Test',
          'macosArm64Test macosX64Test',
          'tvosX64Test tvosSimulatorArm64Test',
          'watchosX64Test watchosSimulatorArm64Test',
          'mingwX64Test',
        ]
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: true
      - name: Test supabase-kt
        run: ./gradlew ${{ matrix.command }} --stacktrace --configuration-cache